# Generated by Django 3.0.6 on 2020-05-30 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hack_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_hacker',
        ),
    ]
