# Generated by Django 3.0.6 on 2020-06-01 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hack_app', '0002_auto_20200601_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('signup_as', models.CharField(max_length=255)),
                ('student_id', models.BooleanField(default=False)),
                ('emp_opportunity', models.BooleanField()),
                ('learn_ab_hackathon', models.CharField(max_length=255)),
                ('github_url', models.URLField()),
                ('how_contribute', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Hackathon_reg',
        ),
    ]
