# Generated by Django 3.0.6 on 2020-06-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack_app', '0003_auto_20200601_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regmodel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='regmodel',
            name='github_url',
            field=models.URLField(blank=True),
        ),
    ]
