# Generated by Django 3.0.6 on 2020-06-01 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hack_app', '0006_auto_20200601_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='regmodel',
            name='votes_total',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voteregs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hack_app.RegModel')),
            ],
            options={
                'unique_together': {('organizer', 'voteregs')},
            },
        ),
    ]
